### ISSUE TITLE
Calibre-Web 0.6.19 Docker导入NewDouban.py搜索结果显示“搜索错误！!”

### ISSUE THREAD

**Issue by Huaweidev** [fugary/calibre-web-douban-api#14]
我的操作步骤如下：

1. SSH登录群晖执行`sudo -i`，输入密码进入root权限。
2. 删除`johngong-calibre-web:/usr/local/calibre-web/app/cps/metadata_provider`下的douban.py。
3. 下载NewDouban.py [v1.1.1](https://github.com/fugary/calibre-web-douban-api/tree/v1.1.1)到home目录。
4. 执行`docker cp NewDouban.py johngong-calibre-web:/usr/local/calibre-web/app/cps/metadata_provider`，在群晖docker里能看到NewDouban.py已经成功复制进去。
5. 重启johngong-calibre-web。
6. 搜索元数据，只能显示“搜索错误！!”是为什么？
![01-11_20-24](https://user-images.githubusercontent.com/10258421/211805638-2ea298c2-cb4d-407c-854b-d02f6a382c1f.png)

**Comment by fugary** [comment]
可能是其他插件影响，NewDouban.py直接放到/home/metadata_provider下面，然后映射/home/metadata_provider:/usr/local/calibre-web/app/cps/metadata_provider，只保留了NewDouban.py插件试试看

**Comment by Huaweidev** [comment]
> 可能是其他插件影响，NewDouban.py直接放到/home/metadata_provider下面，然后映射/home/metadata_provider:/usr/local/calibre-web/app/cps/metadata_provider，只保留了NewDouban.py插件试试看

已经正常映射并只有一个`New Douban Books`标签，仍然出现“搜索错误！！”。
![image](https://user-images.githubusercontent.com/10258421/212045220-fc76089a-69bd-4c28-95db-f3c606eb0402.png)

**Comment by Huaweidev** [comment]
> 可能是其他插件影响，NewDouban.py直接放到/home/metadata_provider下面，然后映射/home/metadata_provider:/usr/local/calibre-web/app/cps/metadata_provider，只保留了NewDouban.py插件试试看

**Comment by Huaweidev** [comment]
github如何打开误关闭的issue？

**Comment by fugary** [comment]
我刚安装了一个最新的johngong-calibre-web是可以获取元数据的，你这个估计得看看docker日志有没有什么其他信息了。

![image](https://user-images.githubusercontent.com/2628844/212227886-98d4329d-d142-429d-99c9-a38f024be12b.png)

**Comment by Huaweidev** [comment]
> 我刚安装了一个最新的johngong-calibre-web是可以获取元数据的，你这个估计得看看docker日志有没有什么其他信息了。

我开启了DEBUG级别日志，然后做了一次获取元数据操作结果是“搜索错误！！”，日志如下：
```
[2023-01-13 18:01:30,376]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2023-01-13 18:01:55,955] DEBUG {cps.updater:329} Stable version: {'version': '0.6.19'}
[2023-01-13 18:02:21,949] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff4c32ceec0>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.douban.com', port=443): Max retries exceeded with url: /search?cat=1001&q=%E5%A4%B1%E6%8E%A7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff4c32ceec0>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/calibre-web/app/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/calibre-web/app/cps/metadata_provider/NewDouban.py", line 36, in search
    return self.searcher.search_books(query)
  File "/usr/local/calibre-web/app/cps/metadata_provider/NewDouban.py", line 88, in search_books
    book_urls = self.load_book_urls_new(query)
  File "/usr/local/calibre-web/app/cps/metadata_provider/NewDouban.py", line 73, in load_book_urls_new
    res = requests.get(url, params, headers=DEFAULT_HEADERS)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.douban.com', port=443): Max retries exceeded with url: /search?cat=1001&q=%E5%A4%B1%E6%8E%A7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff4c32ceec0>: Failed to establish a new connection: [Errno -3] Try again'))
[2023-01-13 18:02:27,001] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff4c33bef20>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.douban.com', port=443): Max retries exceeded with url: /search?cat=1001&q=%E5%A4%B1%E6%8E%A7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff4c33bef20>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/calibre-web/app/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/calibre-web/app/cps/metadata_provider/NewDouban.py", line 36, in search
    return self.searcher.search_books(query)
  File "/usr/local/calibre-web/app/cps/metadata_provider/NewDouban.py", line 88, in search_books
    book_urls = self.load_book_urls_new(query)
  File "/usr/local/calibre-web/app/cps/metadata_provider/NewDouban.py", line 73, in load_book_urls_new
    res = requests.get(url, params, headers=DEFAULT_HEADERS)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.douban.com', port=443): Max retries exceeded with url: /search?cat=1001&q=%E5%A4%B1%E6%8E%A7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff4c33bef20>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by fugary** [comment]
看起来是连不上douban.com，确定下网络是正常的

**Comment by Huaweidev** [comment]
> 看起来是连不上douban.com，确定下网络是正常的

由于群晖防火墙设置了一些规则导致Docker无法与外部通信，添加如下两条规则后问题解决：
1. 允许所有IP的UDP 53端口数据通过；//DNS协议
2. 允许172.17.0.0/16所有协议和端口数据通过；//与Docker通信
