### ISSUE TITLE
拉取书籍元数据，搜索页无结果。。。

### ISSUE THREAD

**Issue by toniexly** [fugary/calibre-web-douban-api#5]
搜书的元数据的时候，搜索页无结果。第一行显示 搜索错误，第二显示 加载中...再后面都是空白。
单选google刮削结果能出来
单选douban不行
双选google和豆瓣也不行。

下面是日志：
[2022-02-24 20:00:54,033] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 133, in metadata_search
    data.extend([asdict(x) for x in future.result()])
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: search() takes from 2 to 3 positional arguments but 4 were given

**Comment by fugary** [comment]
0.6.17问题已修复
